services:
  mysql:
    image: mysql:lts
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      # TZ: Asia/Taipei
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    privileged: true