services:
  traefik:
    image: traefik:v3.4.3
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic
    networks:
      - traefik-net
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  traefik-net:
    driver: bridge