services:
  postgres:
    image: postgres
    container_name: pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
