services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: D:\jellyfin_database
        target: /media
      - type: bind
        source: D:\jellyfin_database\good_music
        target: /media2
    restart: 'unless-stopped'
    extra_hosts:
      - 'host.docker.internal:host-gateway'